name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      OF_BRANCH: master
      OF_ROOT: ${{ github.workspace }}/of

    steps:
      - uses: actions/checkout@v4

      - name: Clone openFrameworks
        run: |
          git clone --depth=1 https://github.com/openframeworks/openFrameworks.git $OF_ROOT
          ls $OF_ROOT

      - name: Install dependencies
        run: |
          cd $OF_ROOT/scripts/linux/ubuntu
          sudo ./install_dependencies.sh -y
          sudo apt-get install -y webp pkg-config

      - name: Download openFrameworks libs
        run: |
          cd $OF_ROOT/scripts/linux
          ./download_libs.sh

      - name: Link addon
        run: |
          ln -s $GITHUB_WORKSPACE $OF_ROOT/addons/ofxWebpAnimation

      - name: Build example-basic
        run: |
          cd $OF_ROOT/addons/ofxWebpAnimation/example-basic
          make -j$(nproc)

  build-macos:
    runs-on: macos-latest
    env:
      OF_BRANCH: master
      OF_ROOT: ${{ github.workspace }}/of

    steps:
      - uses: actions/checkout@v4

      - name: Clone openFrameworks
        run: |
          git clone --depth=1 https://github.com/openframeworks/openFrameworks.git $OF_ROOT
          ls $OF_ROOT

      - name: Install dependencies (homebrew)
        run: |
          brew update
          brew install webp pkg-config

      - name: Download openFrameworks libraries
        run: |
          cd $OF_ROOT/scripts/osx
          ./download_libs.sh

      - name: Link addon
        run: |
          ln -s $GITHUB_WORKSPACE $OF_ROOT/addons/ofxWebpAnimation

      - name: Build example-basic
        run: |
          cd $OF_ROOT/addons/ofxWebpAnimation/example-basic
          make -j$(sysctl -n hw.logicalcpu)
