name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      OF_BRANCH: master
      OF_ROOT: ${{ github.workspace }}/of

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebp-dev pkg-config libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxcursor-dev libxrandr-dev libxi-dev libxinerama-dev libxxf86vm-dev libxft-dev libxext-dev libxfixes-dev libxcomposite-dev libasound2-dev libpulse-dev libudev-dev

      - name: Clone openFrameworks
        run: |
          git clone --depth=1 --branch=${OF_BRANCH} https://github.com/openframeworks/openFrameworks.git of

      - name: Build openFrameworks core
        run: |
          cd of/scripts/linux
          ./compileOF.sh -j$(nproc)

      - name: Link addon
        run: |
          ln -s $GITHUB_WORKSPACE $OF_ROOT/addons/ofxWebpAnimation

      - name: Build example-basic
        run: |
          cd $OF_ROOT/addons/ofxWebpAnimation/example-basic
          make -j$(nproc)

  build-macos:
    runs-on: macos-latest
    env:
      OF_BRANCH: master
      OF_ROOT: ${{ github.workspace }}/of

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install webp pkg-config

      - name: Clone openFrameworks
        run: |
          git clone --depth=1 --branch=${OF_BRANCH} https://github.com/openframeworks/openFrameworks.git of

      - name: Build openFrameworks core
        run: |
          cd of/scripts/osx
          ./compileOF.sh -j$(sysctl -n hw.logicalcpu)

      - name: Link addon
        run: |
          ln -s $GITHUB_WORKSPACE $OF_ROOT/addons/ofxWebpAnimation

      - name: Build example-basic
        run: |
          cd $OF_ROOT/addons/ofxWebpAnimation/example-basic
          make -j$(sysctl -n hw.logicalcpu)
