name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      OF_BRANCH: master
      OF_ROOT: ${{ github.workspace }}/of

    steps:
      - uses: actions/checkout@v4

      - name: Install extra deps (addon-specific)
        run: sudo apt-get update && sudo apt-get install -y libwebp-dev pkg-config

      - name: Clone openFrameworks
        run: git clone --depth=1 --branch=${OF_BRANCH} https://github.com/openframeworks/openFrameworks.git of

      - name: Download oF core libraries
        run: |
          cd of/scripts/linux
          ./download_libs.sh

      - name: Install oF dependencies (official CI script)
        run: |
          cd of/scripts/ci/linux64
          ./install.sh

      - name: Build openFrameworks core (official CI script)
        run: |
          cd of/scripts/ci/linux64
          ./build.sh

      - name: Link addon
        run: ln -s $GITHUB_WORKSPACE $OF_ROOT/addons/ofxWebpAnimation

      - name: Build example-basic
        run: |
          cd $OF_ROOT/addons/ofxWebpAnimation/example-basic
          make -j$(nproc)
